using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace VirtualRealty
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {

        public static List<Listing> Listings;

        public static ListingsPage LP = new ListingsPage();
        public static SavedSearches savedSearchesPage;
        public static MapView MapViewPage = new MapView();

        public MainWindow()
        {
            Listings = CreateListings();

            LP.SetListings(Listings);

            InitializeComponent();
            
            Switcher.pageSwitcher = this;
            Switcher.Switch(LP);  //initial page   
        }

        public void Navigate(UserControl nextPage)
        {
            this.Content = nextPage;
        }


        /*
         * Method used to create disgusting list of Listings
         */
        private List<Listing> CreateListings()
        {
            //TODO
            List<Listing> ToReturn =  new List<Listing> ();
            ToReturn.Add(new Listing(true, 1050000, "1510-1001 13th Ave SW #1510, Calgary, AB T2R 0K7", DateTime.Parse("2021-11-15"), 3, 2, 2583, HomeType.Condo, "Stunning like new Penthouse unit priced to sell! Over 2500 sqft of luxury living in the Beltline, walk to work in the core and to all the attractions of17th Avenue. The sellers have done a complete renovation including gutting the kitchen and tearing down walls, this is truly an open concept livingspace. Gorgeous new island with marble counter tops, new cabinets and appliances. Hardwood throughout. Media room that could be 4th bedroomif you wanted. Raised sitting area, the perfect place for pre-dinner cocktails and admiring the views. Master ensuite was just finished and includessuch fine, thought out details as back lit mirrors, deep stand alone soaker tub, massive walk in shower and make up console around the corneraway from the steam. 2 large balconies for BBQ and relaxing in the fresh air with views of the Calgary Tower and to the South. 2 titled parkingstalls. Lots of storage.", false, "Underground", true, 1981, "Park", true, true, true, true, true, new List<string>()));
            ToReturn.Add(new Listing(true, 84000, "4328 W 4th St NW #202, Calgary, AB T2K 1A2", DateTime.Parse("2021-11-15"), 1, 1, 473, HomeType.Apartment, "Judicial sale! Large 1 bedroom condo located Highland Park. Good sized kitchen and dining area. Living room is bright, east facing towards the park. Bedroom is generously sized with plenty of closet space. Private patio with no neighbours behind. Fantastic location close to many amenities including Tim's, 7-Eleven, a variety of dining options, shopping, and public transit. Short distance to downtown!", false, "Off-Street", false, 1986, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 270000, "180 S Prestwick Acres Ln SE, Calgary, AB T2Z 3Y2", DateTime.Parse("2021-11-15"), 2, 2, 1063, HomeType.Townhouse, "Welcome to this Superb and very well maintained townhome with a location you will love at the Mosiac in McKenzie Towne! Easy access to all your shopping needs, parks, schools, playgrounds, open spaces and a friendly active neighbourhood! Be the first to enjoy the BRAND NEW LUXURY VINYL PLANK flooring that is incredibly durable which will make your life easier and enhance any look or style you choose to decorate with as these beautiful warm light tones give you endless options! Also BRAND NEW is all the amazing soft and luxurious carpet on the stairs heading to the upper level and throughout the upper floor! Not only has all the flooring been replaced this entire home has just been Professionally Painted with a beautiful designer colour! Features you will also see in this home are the desirable open floor plan, 2 piece bath on main level, well functioning kitchen with Maple Cabinetry and clean appliances. Heading down to lower level leads to back door to your own fenced in backyard with patio area to set up a cozy outdoor space! Lots of closet and storage space before the stairs to your laundry and utility  room! You will have plenty of EXTRA STORAGE IN YOUR ATTACHED OVERSIZED SINGLE GARAGE, freshly painted as well! Upper level has a flex space room enough for a computer desk or chair for a reading area! Large 4 piece bath between two well appointed and generous sized bedrooms each with their own spacious WALK IN CLOSETS! This home is ready for its new family, come check it out! Don't miss out! Book a showing today!", false, "Garage", false, 2001, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 1600000, "136 NE Edelweiss Dr NW, Calgary, AB T3A 3P6", DateTime.Parse("2021-11-02"), 5, 5, 3059, HomeType.House, "This spectacular Estate home is truly one to view, as if you're not already sold on the stunning, snow-capped, sweeping mountain views, the location or the neighbourhood, it’s likely the interior & layout that will put you over the edge. Completely re-designed from the studs, this 5 bedroom, 4.5 bathroom family home is truly set to impress the most discerning of buyers. As the amazing curb appeal brings you in, you will instantly feel a sense that this home is right for you & your family. The back-drop views from all 3 levels is truly something to see, showcasing a sprawling main floor w/ grand entryway, massive entertainment-gourmet kitchen & island, family room, main floor office, informal + semi-formal dining areas & family room that leads you to your private, covered patio, overlooking Calgary’s most stunning views. Main floor, fully redesigned laundry/custom mudroom + 2pc powder room complete the main. The upper level leads to an open, family bonus room or informal office, 4 large bedrooms, 2 w/ en suites, heated floors, and walk-in closets, incl your own 5pc master retreat (w/steam shower) & unbelievable views! The lower walkout level has a 5th bedroom, another 4pc bath, family room, games room, gym and walks out to a fully landscaped, private backyard, with access to the off-leash ravine, that your family will absolutely fall in love with…A/C, Miele appliances, Irrigation, 2 furnaces, large, oversized epoxy garage, new triple glazed windows, endless custom built-ins... the list goes on.  This lovely home is all about location, quality, functionality, comfort, views, and being close to everywhere you would need to be. Haven’t considered the estate side of Edgemont before? You may want to now. Priced aggressively to move and it’s ready tomorrow… The quick, MULTI-MEDIA VIDEO IS A MUST SEE, so is this stunning home.", false, "Garage", false, 1985, "Stunning", true, true, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 1690000, "9 S Hamptons Vw NW, Calgary, AB T3A 6M1", DateTime.Parse("2021-10-14"), 5, 5, 4530, HomeType.House, "Welcome to the exclusive gated community of VIA ULTIMA Hamptons, an enclave of 10 extra ordinary homes built by the award-winning builder Calbridge Homes. Perched above the Hamptons Golf Course with spectacular majestic views of the fairways and ponds, this 5-bedroom, 2 storey, with triple attached garage, boasts over 6,300 sq ft of luxury living space. Grand open design highlighted by the impressive great room with soaring 20 ft ceilings inundating the home with natural light. The grand chef’s kitchen is truly the heart of the home, perfect for entertaining and social gatherings, it will satisfy the most discerning chef. It is equipped with high-end stainless steel appliances including Sub Zero fridge/freezer, Miele dishwasher, Viking cooktop, double wall oven with warming drawer, maple cabinets, granite counters, island, breakfast bar, 2 extra large pantries and bright eating area with deck access. Love the formal dining room featuring coffered ceilings and a butler’s pantry. Your business office is conveniently located on the main floor with built-ins and shares a double-sided fireplace with the great room. Wander up the open riser spiral staircase while listening to the cascading waterfall on your way to the 2nd floor library, which overlooks the main floor. The luxurious appointed owner's suite boasts a double-sided fireplace and spa like 5 piece en suite complete with steam shower and walk-in closet. Wake up and step onto your covered balcony and enjoy the breath-taking views overlooking the Hamptons golf course. The other 3 bedrooms are spacious and have en suite baths. The bonus room is perfect for a late-night movie. The fabulous lower-level features in-floor heating, large family room, media/rec room, bar, 5th bedroom, sauna, full bath and home gym with Gator Elite Flex flooring system. Your spacious landscaped yard features your own private sport court, stone patio and firepit. Additional features include the Theatre system, multi-room audio system, central air conditioning, motorized window covering control, central vacuum system, 2 electronic air cleaners, reverse osmosis water system, water softener and sprinkler system. This is the perfect family home!!", false, "Garage", false, 2007, "Lakeview", true, true, false, true, false, new List<string>()));
            ToReturn.Add(new Listing(true, 5400000, "711 Bearspaw Village Dr, Rocky View County, AB T3L 2P3", DateTime.Parse("2021-05-08"), 5, 6, 5566, HomeType.House, "A RARE opportunity to own this luxurious CUSTOM-BUILT executive country estate minutes from Calgary.  Welcome to 711 Bearspaw Village Drive. This MAGNIFICENT walk-out perched high atop the BOW VALLEY corridor provides an incredible combination of outstanding features, exceptional construction and EXTENSIVE, meticulous landscaping featuring numerous ponds and waterfalls.  This home is a blend of PRIVATE, TRANQUIL yet rugged beauty set in amongst a forest of trees and Rocky Mountain backdrop. With over 8300 sq' of LUXURY and understated ELEGANCE there is no shortage of special areas in this home. The great room with SOARING 30' ceilings provides a wonderful area to take in mother nature, the FLOOR TO CEILING fireplace with rock surround adds to the warmth of this AWE-INSPIRING room. The master RETREAT located on the main floor, includes a 2-way FIREPLACE, lounge area surrounded by windows and ACCESS to the covered WRAP AROUND PORCH to enjoy your morning coffee. The en suite along with a soaker tub set in SLATE TILE surround, double entry walk-in closet is a perfect spa like oasis.  The BRIGHT kitchen WITH AMAZING VIEWS features off white cabinetry, high-end stainless-steel appliances, granite counters and a well positioned island is set up perfectly for your ENTERTAINING. A spacious area with breakfast bar, kitchen nook and a formal dining room adjacent to kitchen, butler’s pantry and WINE ROOM blend in seamlessly to make this a FAVOURITE part of the home.  THE COVERED WRAP AROUND VERANDA CONTINUES AROUND THE ENTIRE HOME, just pick your favourite  view - grab a coffee - and take in all nature has to offer.  The second story of the house is divided into 3 sections, a GRAND OPEN RISER STAIRCASE leads you up to a landing complete with a FIREPLACE. Up the stairs to the right you will find an OPEN LOFT with a den/study and bedroom. Left of the stairwell landing you will find 2 LARGE bedrooms, one with a VIEW to the west and the other to the east taking in the vast forest of trees, ponds, bridges and STREAMS. Up the stairs to the cozy loft above the triple car garage is a STUNNING GUEST SUITE that will have your guests longing to overstay. This WARM and INVITING room can be accessed from the garage entrance behind the kitchen, features a 4 WAY FIREPLACE, lounge area, ENSUITE & WET BAR.  The WALKOUT basement is an ENTERTAINER'S DREAM with a media/theatre room, recreation room complete with a billiards table and pinball machines, LARGE WET BAR & tv's to enjoy the game, family room and exercise room.  The outdoor COVERED PATIO areas accessible from the basement is the perfect place to unwind and watch the SUNSET. All furnishings and 2013 Lexus LS 460 4 door AWD - 21,599 km included.", false, "Garage", false, 2001, "Stunning", true, true, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 234900, "6503 SE Ranchview Dr NW #25, Calgary, AB T3G 1P2", DateTime.Parse("2021-10-01"), 3, 2, 999, HomeType.Townhouse, "BACKING ON TO AN OFF-LEASH DOG PARK, this MOVE-IN READY, 3 bedroom/2 bath townhouse is waiting for its new OWNER!  This unit has newer carpet on main level, upper level and stairways, newer linoleum in both bathrooms, and natural pine wood floors in kitchen and hallway. Main floor has an open kitchen with plenty of cabinets, NEW COUNTERTOPS, new stainless steel stove and dishwasher.  Wood-burning fireplace in the living room will keep you cozy all winter long.  The 2nd floor has a master bedroom with walk-in closet.  Two additional bedrooms and a 4 piece bath complete the upper level.  Basement is fully developed w/huge family room, games/rec room, laundry room & 3 piece bath.  Extra insulation in attic to keep you warm in the winter and cooler in the summer. Unit also has newer vinyl windows, front door, screen door and patio doors. Roof and eaves were replaced in 2008 and the exterior painted in 2016.  Backyard is fully fenced.  This is a great property for an INVESTOR or FIRST-TIME HOME BUYER/YOUNG FAMILY.  Parking is located close to the unit.", false, "Parking Lot", false, 1978, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 330000, "448-8535 Bonaventure Dr SE #448, Calgary, AB T2H 2R7", DateTime.Parse("2021-10-25"), 1, 2, 1001, HomeType.Condo, "Welcome to this beautiful top floor unit in Sierra's of Heritage. This well maintained space is flooded with natural light coming  from a wall of west facing windows.  You can enjoy a  spectacular mountain view from  the living room , as well as the master bedroom and your large covered balcony will wow you with both mountain and downtown views. The moment you step through the doors you will appreciate the 9 foot ceilings that make this open space feel even more grand. Functional layout of an open kitchen, dining room and living space will be great for entertaining, as well as cozying up around your gas fireplace. Beautiful french doors lead you to the large den area that can serve as a home office, spare bedroom or a hobby room.  The master bedroom is oversized and can easily fit a king size bed. Ensuite bathroom provides tons of space and a walk-in closet is large and fitted with shelves already.  This unit has an additional 3 piece bathroom and a laundry/storage room.  You will find 2 parking stalls that are assigned to this unit to be conveniently located  near the elevators. This well managed , 29+ adult building is quiet and hosts tons of amenities like swimming pool, hot tub and workout room to keep you fit and moving.   Games room, billiard space,  library and a large well equipped workshop will make sure you continue  with your hobbies.  Guest suits,  banquet hall with a kitchen allows you to host your family and stay social.  Many spaces in this building, like craft and media room or games room  to meet like minded people and new friend.   Lets not forget about the location of this condominium - close to all the shopping centers, medical clinics, hospital, malls, coffee shops and restaurants.", false, "None", false, 2000, "Innercity", false, false, true, false, true, new List<string>()));
            ToReturn.Add(new Listing(true, 249000, "7638 W 27th St SE, Calgary, AB T2C 1E7", DateTime.Parse("2021-09-28"), 4, 1, 920, HomeType.Townhouse, "Great potential! This home was renovated a few years ago. Parts of the home seem tired but with a little bit of love this place could shine again! It has 3 bedrooms in the upstairs and one bedroom downstairs that can be used as a bedroom (you may want to put a windows in it), the kitchen has been updated and the living room is spacious where you can spend lots of time with your friends and family! It is vary rare to get a home at this price with an oversized single garage. It also  has a great big side yard! There are tenants living in the home and they would be happy to stay living there. This home is also close to where the new green line will be coming through - so you will get access to rapid transit to downtown! Come take a look!", false, "Garage", false, 1971, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 2095000, "841 NE Royal Ave SW, Calgary, AB T2T 0L4", DateTime.Parse("2021-11-16"), 3, 4, 3370, HomeType.House, "This remarkable brick and sandstone residence was built for Reuben Rupert Jamieson, Calgary's Mayor (1908-1910) in 1912 & is situated on a private 11,051 sq. ft. lot in prestigious Mount Royal. With over 4,608 sq. ft of developed living space on 4 levels, this charming family home has been completely renovated preserving the original character of the home while providing all of the modern conveniences. The gracious front veranda lures you in & opens up to the large foyer & all of the formal living spaces throughout featuring onsite finished Brazilian cherry finished hardwood floors, an expansive living room with a gas fireplace surrounded in contemporary tile & coffered ceilings with hidden lighting, elegant French doors open to the formal dining area with ample room to host a multitude of special occasions. The updated, gourmet kitchen with amber stained maple cabinets, quartz counter tops, top of the line stainless steel appliances & in-floor heating sides onto the large nook area. Updated 2 piece powder room is conveniently tucked away beyond a full wall of additional floor to ceiling cabinetry. There are 3 bedrooms & a 4 piece bath on the second level. The spacious master bedroom has a generous sitting area with unobstructed downtown views, 2 walk-in closets & a luxurious 5 piece ensuite with in-floor heat, dual sinks, jacuzzi tub & separate steam shower. 2 additional bedrooms, large bonus/studio space and office/den (each could be used as additional bedrooms), 4 piece main bathroom & laundry complete the second level. Follow the final set of stairs to the 3rd level with more spectacular downtown views, could be used as a family/media room or additional bedroom & provides access to a fabulous roof top terrace with additional downtown views. The fully developed lower level showcases a large recreation room, wine cellar with ample space for your private collection, home gym (could be used as an additional bedroom), 4 piece guest bath & kitchenette. Additional features include an oversized front veranda, large brick patio in the landscaped backyard with annuals, perennials and large trees for added privacy, outstanding city views from the second & third levels including the roof top terrace. Conveniently located within walking distance to shopping & dining on trendy 17th Avenue, excellent schools, city transportation & a short walk/drive/bike to the core!", false, "Garage", false, 1912, "Downtown", true, true, false, true, false, new List<string>()));
            ToReturn.Add(new Listing(true, 459000, "272 Cornerstone Pass NE, Calgary, AB T3N 1G3", DateTime.Parse("2021-04-20"), 3, 3, 1497, HomeType.Townhouse, "Almost like new, beautiful Open Concept Home in the Desirable Community of Cornerstone.  The House features great size living space on the main, a big dining space and kitchen to the rear of the home with big windows. Kitchen Counter space is huge.  Upstairs features Master bedroom with 4PC en-suite bath and 2 other big size bedrooms and another 4 PC bath.  Laundry is upstairs. SEPARATE ENTRANCE for the undeveloped basement.  2 min Walk to park and playground. 5 min drive to huge commercial plaza with banks, groceries, restaurants etc.", false, "Parking Lot", false, 2017, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 334900, "3228 E Rae Cres SE, Calgary, AB T2A 1Y3", DateTime.Parse("2021-11-03"), 3, 2, 1003, HomeType.House, "Tucked away on this quiet crescent in Radisson Heights is this charming one owner home, within minutes to neighbourhood schools, parks & International Avenue. Fully finished 1960's bungalow with 3 bedrooms & hardwood floors, sunny eat-in oak kitchen & fenced West backyard with gardens & oversized single detached garage. Great family-friendly floorplan featuring inviting living room with hardwood floors & built-in bookcases, with wonderful kitchen with pantry & black/white appliances including cooktop stove & built-in convection oven. Hardwood floors in the 3 main floor bedrooms & the full bath has been beautifully updated with tile floors, walk-in shower & vessel sink. Lower level is finished with office & craft room, 2 piece bath, rumpus room with bar & workshop/laundry/storage area. Backyard with brick patio & retractable awning is the perfect spot to relax & enjoy the outdoors, & for the greenthumb in the family there are fruit trees & plenty of gardening space. Some updates in last 15 years: windows, hot water tank (2011), roof (@ 9 years) & kitchen (2020). Prime location in the heart of this popular mature community with easy access to Memorial Drive to take you downtown, Deerfoot Trail & beyond!", false, "Garage", false, 1966, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 435000, "128 S Pinetree Rd NE, Calgary, AB T1Y 1K2", DateTime.Parse("2021-10-22"), 5, 3, 1449, HomeType.House, "Perfect for the first home owner or investment property located on the quiet street of Pineridge. This completely renovated in the last few years home features open style Bungalow on large lot with RV pad,  oversized double detached garage. Kitchen features granite countertops, stainless steel appliances, living and dining rooms, 3 bedrooms, the master bedroom comes complete with 2 pc ensuite. Fully finished 2 bedrooms illegal suite in basement with separate entrance, share laundry room and newer hot water tank. A must see ! Book your appointment today.", false, "Garage", false, 1974, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 235000, "55 E Falconer Ter NE, Calgary, AB T3J 1W3", DateTime.Parse("2021-09-18"), 3, 2, 1112, HomeType.Townhouse, "Welcome to 55 Falconer Terrace! This one is truly a hidden gem with pride of ownership throughout the home. As you come in the front entrance you are greeting by rich, warm hardwood floors. The living room is bathed in natural light and invites you to relax after a hard days work. The kitchen is beautiful with updated cabinets with wine rack, countertops, new taps, glass backsplash and top of the line SS appliances. An updated half bath completes the floor. Head upstairs and you will find 3 bedrooms with a really nice sized primary bedroom and another updated 4pc bath. Head out to your West facing, fenced backyard to enjoy your private oasis. You can imagine enjoying a glass of wine and watching the sun set.  Updates include – hardwood floors (main), porcelain floors (kitchen & ½ bath), door hardware, low flow toilets, 2 x screen doors for air flow, fence painted (2021). As well complex updates include – windows & doors (2012), roof, downspouts & eaves (2017), playground (2017), outdoor lighting (2016) and vinyl siding to be replaced by condo board (current). This complex is well run with all major updates completed and condo fees are still low.  You will not find a home that is more cared for than this one. Great location with quick access to major routes and close to shopping, schools and other amenities. What are you waiting for? Book your private showing today!", false, "Parking Lot", false, 1980, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(true, 829900, "58 E Skyview Point Rise NE, Calgary, AB T3N 0G9", DateTime.Parse("2021-11-01"), 7, 7, 3212, HomeType.House, "Spectacular well maintained home! 5 above grade beds, each has their own bathroom plus 2 beds legal basement suite w/ walk up entrance. This home offers a total of 4,099 sqft living space including the basement! If you have a large family, THIS IS FOR YOU! A THREE STOREY home with a total of 3 kitchens! You can live up and rent down. Main floor boasts an open concept layout w/ a large island kitchen w/walk thru pantry & GRANITE counters. 2 kitchens one being the spicy kitchen. A Flex room & an extended breakfast nook. Lots of upgrades. 9' ceilings. Hardwood & tile cover the floors. Upgraded appliances & lighting fixtures, extended height cabinets. 2nd level offers 4 beds, a bonus room & upper laundry. 3rd loft level features an additional bonus room, bedroom & 4pc bath. The basement is legal & has 2 beds, 4pc bath. It has its own kitchen, washer & dryer & separate entrance. This home is backing on to a walkpath with green space. Backyard is fenced and secure. A block away from school & playgrounds. The garage is 2 car oversize w/ a lot of shelvings. Complete with all the built green features that makes this home right for you!", false, "garage", false, 2013, "None", true, true, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(false, 1369, "15 Grier Pl NE, Calgary, AB T2K 5Y5", DateTime.Parse("2021-04-13"), 1, 1, 876, HomeType.Apartment, "Message us about our move-in bonuses, which include gift cards!* Steps away from a wide variety of restaurants, retail stores, and parklands. Close by City of Calgary Toboggan Hill, Walmart, Canadian Tire, McCall Lake Golf Course, Rona, and more. Convenient access to McKnight Blvd NE, Deerfoot Trail, and Calgary International Airport. Occupancy for the unfurnished 1-bed and 2-bed units. Water & heat included. Included modern appliances: fridge, microwave, stove, dishwasher, and range hood. Parking available for rent. Staged photos are for illustrative purposes only. Suite finishes and layouts may vary by availability. Do you have a vacant unit? Inquire us about our cost-effective tenant placement solutions for landlords and realtors in Ontario!  *Terms & conditions apply", false, "None", false, 1980, "None", true, true, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(false, 1365, "Varsity Place Apartments, # 773175, 3607 49th St NW, Calgary, AB T3A 2H3", DateTime.Parse("2021-11-15"), 2, 1, 840, HomeType.Apartment, "Rent today and save up to 2 months on rent with the most exclusive rates on TELUS Optik TV and High-Speed Internet. Live your life uninterrupted at Varsity Place Apartments where you come first! Students receive a $300 move in bonus! Virtual Showings Available! Location, location, location! Varsity Place Apartments is conveniently located next to Market Mall and the University of Calgary. Super quick and easy access to Crowchild Trail and Shaganappi Trail. With green spaces, parks, and playgrounds, enjoy plenty of outdoor living. WORRY-FREE LIVING -24-hour customer service team -On-site cleaning staff-On-site landscaping and snow removal-On-call emergency maintenance-On-site security and video surveillance WHAT SETS US APART-$399 security deposit -Community involvement opportunities-Exclusive discounts with local businesses*-Free resident events- Referral program LIVE HERE-Functional 1 and 2 bedroom suites-Standard and upgraded suites -12-month lease terms-Outdoor parking -Smart Card System in laundry facilities Start getting to know the Boardwalk community by following @bwalkcommunity on Facebook and Instagram! *Save $89.99 on your first 3 HelloFresh orders, 10% off online Rosso Coffee Roasters purchases, and more! Note: Information posted, including suite availability, security deposits, rental rates and incentives are subject to change without notice or may vary by suite type. Current residents can contact the Customer Service Representative to discuss lease renewal options. Suites and floor plans may not be as shown. Some conditions apply. Rental rates listed are net and include current incentives when applicable. Incentives advertised are for new applicants. Internal transfers are subject to conditions found within the Transfer Agreement.", false, "Parking Lot", true, 2001, "Downtown", true, true, false, false, true, new List<string>()));
            ToReturn.Add(new Listing(false, 5500, "1240 N 18a St NW, Calgary, AB T2N 2H4", DateTime.Parse("2021-09-05"), 5, 4.5, 3777, HomeType.House, "A stunning corner lot location in Briar Hill/Hounsfield Heights sits this impressive home. Showcasing superb finishing & detailing this family home provides over 5,400 sq ft of developed living space featuring functionality & practicality.The Brazilian cherry hardwood floors take you through an open floor plan boasting a front den highlighted by curved glass french doors, formal dining room and a sprawling living room with a linear stone gas fireplace and french doors that extend out to the patio retreat.   A timeless kitchen will bring out your inner chef, providing you with an ideal space to prepare and entertain. The area features a grand centre island, quartz countertops, dual dishwasher, dual wall ovens, induction cook top, breakfast nook & walk-in butlers style pantry.   An ideal mud room is situated off the kitchen and is fully equipped with customized built-ins and a laundry room.  The curved staircase brings you to an upper level which encompasses a bonus room/fourth bedroom and three generous size bedrooms all providing you with ample closet space.  The master retreat can be emphasized by its generous size and provides you with elevated views of the downtown, sitting area, custom walk-in dressing room & tranquil ensuite. The ensuite features the ultimate soaker tub & a steam shower to soothe all your troubles away.  The lower level of this home has been updated and houses two additional bedrooms, full bathroom, additional laundry room, games area with wet bar, and recreational space. Many additional features include hydronic in-floor heating, private backyard oasis with deck seating, triple detached garage, and is minutes to the LRT, North Hill Mall, parks, and elementary school. This is a must see!", false, "Garage", true, 2005, "None", true, true, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(false, 1019, "915 44th St SE, Calgary, AB T2A 5K7", DateTime.Parse("2021-02-27"), 1, 1, 522, HomeType.Apartment, "Message us about our move-in bonuses, which include 1 month free rent on a 13 month lease!* Steps away from a wide variety of restaurants, retail stores, and parklands. Close by Marlborough Mall, Bob Bahan Aquatic & Fitness Centre, Elliston Park, TransCanada Centre, Southview Center, Forest Lawn Library, shops on International Avenue, and more. Convenient access to Deerfoot Trail, Stoney Trail, 17 Ave SE, 16 Ave NE, and Calgary International Airport.  Occupancy for the unfurnished 1-bed units. Water, hydro & heat included. Included appliances: fridge, stove, and range hood. Parking available for rent. Staged photos are for illustrative purposes only. Suite finishes and layouts may vary by availability.  Do you have a vacant unit? Inquire us about our cost-effective tenant placement solutions for landlords and realtors in Ontario! *Terms & conditions apply", false, "Parking Lot", true, 1993, "None", true, false, false, false, false, new List<string>()));
            ToReturn.Add(new Listing(false, 1000, "Pineridge Apartments, # 772706, 433 Pinestream Pl NE, Calgary, AB T1Y 3A5", DateTime.Parse("2021-11-17"), 1, 1, 625, HomeType.Apartment, "Rent today and save up to 2 months on rent with the most exclusive rates on TELUS Optik TV and High-Speed Internet. Live your life uninterrupted at Pineridge Apartments where you come first! Virtual Showings Available! Location, location, location! Pineridge Apartments is conveniently located next Village Square Leisure Centre and Pinecliff Park. Super quick and easy access to transit and Deerfoot Trail. With green spaces, parks, and playgrounds, enjoy plenty of outdoor living. WORRY-FREE LIVING -24-hour customer service team -On-site cleaning staff-On-site landscaping and snow removal-On-call emergency maintenance-On-site security and video surveillance WHAT SETS US APART-$399 security deposit -Community involvement opportunities-Exclusive discounts with local businesses*-Free resident events- Referral program LIVE HERE-Functional 1 ,2 and 3 bedroom suites-Standard and upgraded suites -12-month lease terms-Underground parking -Smart Card System in laundry facilities Start getting to know the Boardwalk community by following @bwalkcommunity on Facebook and Instagram! *Save $89.99 on your first 3 HelloFresh orders, 10% off online Rosso Coffee Roasters purchases, and more! Note: Information posted, including suite availability, security deposits, rental rates and incentives are subject to change without notice or may vary by suite type. Current residents can contact the Customer Service Representative to discuss lease renewal options. Suites and floor plans may not be as shown. Some conditions apply. Rental rates listed are net and include current incentives when applicable. Incentives advertised are for new applicants. Internal transfers are subject to conditions found within the Transfer Agreement.", false, "Underground", true, 1999, "None", true, true, false, true, true, new List<string>()));

            return ToReturn;
        }

        public static void CreateInitialSavedSearches()
        {
            SavedSearches.savedSearches = new List<SavedSearch>();

            SavedSearch savedSearch1 = new SavedSearch
            {
                SearchName = "Condos in Calgary",
                LocationSearchString = "Calgary",
                HomeType = new List<HomeType>
            {
                HomeType.Condo,
                HomeType.Apartment
            },
                MinPrice = 100000,
                MaxPrice = 500000,
                MinSqFt = 500,
                MaxSqFt = 2000,
                LastAccessed = DateTime.Parse("10/6/2021"),
                DateSaved = DateTime.Parse("10/3/2021")
            };

            SavedSearches.savedSearches.Add(savedSearch1);

            SavedSearch savedSearch2 = new SavedSearch
            {
                SearchName = "Mansions",
                LocationSearchString = "Airdrie",
                HomeType = new List<HomeType>
            {
                HomeType.House,
            },
                MinPrice = 5000000,
                MinSqFt = 3000,
                MaxSqFt = 10000,
                MinBeds = 5,
                MinBaths = 4,
                LastAccessed = DateTime.Parse("6/10/2021"),
                DateSaved = DateTime.Parse("3/10/2021")
            };

            SavedSearches.savedSearches.Add(savedSearch2);
        }
    }
}
